<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>WhatsApp Your MP</title>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>
<link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->

<center>
  <a href="https://saveindianforests.thereisnoearthb.com/" style="font-size: xx-large;"><b><h1>#SaveIndianForests</h1></b></b></a>

  <img width="100%" src="header.jpg" alt="Picture of There Is No Earth B community cleaning up Ridge forest in delhi">
</center>
  <h2 style="font-size: x-large;">WhatsApp Your MP 👇🏿</h2>


  <div id="cardContainer"></div>
<!-- partial -->
  <script  src="./script.js"></script>

</body>
</html>
